alter table PLACEUR_CITY add constraint FK_PLACEUR_CITY_LOCATION foreign key (LOCATION_ID) references PLACEUR_LOCATION(ID);
create unique index IDX_PLACEUR_CITY_UK_LOCATION_ID on PLACEUR_CITY (LOCATION_ID) where DELETE_TS is null ;
create index IDX_PLACEUR_CITY_LOCATION on PLACEUR_CITY (LOCATION_ID);
